manipulator:
  joint_names: ['shoulder_rotation', 'forearm_rotation', 'arm_rotation', 'wrist_rotation', 'wrist_pitch', 'gripper_rotation', ]

# Joint states controller settings
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Joint position controllers settings
  shoulder_rotation_controller:
    type: velocity_controllers/JointVelocityController
    joint: shoulder_rotation
    # pid: {p: 10.0, i: 10.0, d: 0.0}

  forearm_rotation_controller:
    type: velocity_controllers/JointVelocityController
    joint: forearm_rotation
    # pid: {p: 1000.0, i: 100.0, d: 0.0}

  arm_rotation_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_rotation
    # pid: {p: 1000.0, i: 5.0, d: 0.0}

  wrist_rotation_controller:
    type: velocity_controllers/JointVelocityController
    joint: wrist_rotation
    # pid: {p: 10, i: 5.0, d: 0.0}

  wrist_pitch_controller:
    type: velocity_controllers/JointVelocityController
    joint: wrist_pitch
    # pid: {p: 20.0, i: 5.0, d: 0.0}

  # gripper_rotation_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: gripper_rotation
  #   pid: {p: 10.0, i: 0.5, d: 0.0}

  gazebo_ros_control:
    pid_gains:
      shoulder_rotation: {p: 4.5, i: 5.0, d: 0.01, i_clamp_min: -1.0, i_clamp_max: 1.0}
      forearm_rotation: {p: 50, i: 900.0, d: 0.001, i_clamp_min: -80.0, i_clamp_max: 80.0}
      arm_rotation: {p: 20.0, i: 4.25, d: 0.05, i_clamp_min: -100.0, i_clamp_max: 100.0}
      wrist_rotation: {p: 0.2, i: 2.0, d: 0.0, i_clamp_min: -10.0, i_clamp_max: 10.0}
      wrist_pitch: {p: 1.5, i: 30.0, d: 0.0001, i_clamp_min: -10.0, i_clamp_max: 10.0}
      # gripper_rotation: {p: 0.1, i: 15.0, d: 0.0001, i_clamp_min: -0.5, i_clamp_max: 0.5}