manipulator:
  joint_names: ['shoulder_rotation', 'forearm_rotation', 'arm_rotation', 'wrist_rotation', 'wrist_pitch', 'gripper_rotation', ]

# Joint states controller settings
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Joint velocity controllers settings
  shoulder_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: shoulder_rotation
    pid: {p: 20.0, i: 1.0, d: 0.001, i_clamp_min: -10.0, i_clamp_max: 10.0}

  forearm_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: forearm_rotation
    pid: {p: 200.0, i: 50.0, d: 0.01, i_clamp_min: -5.0, i_clamp_max: 5.0}

  arm_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: arm_rotation
    pid: {p: 50.0, i: 200.0, d: 0.0001, i_clamp_min: -100.0, i_clamp_max: 100.0}

  wrist_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: wrist_rotation
    pid: {p: 5.0, i: 8.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

  wrist_pitch_controller:
    type: effort_controllers/JointVelocityController
    joint: wrist_pitch
    pid: {p: 17.0, i: 10.0, d: 0.0001, i_clamp_min: -1.0, i_clamp_max: 1.0}

  gripper_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: gripper_rotation
    pid: {p: 1.1, i: 0.5, d: 0.0001, i_clamp_min: -2.0, i_clamp_max: 2.0}