manipulator:
  joint_names: ['shoulder_rotation', 'forearm_rotation', 'arm_rotation', 'wrist_rotation', 'wrist_pitch', 'gripper_rotation', ]

# Joint states controller settings
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Joint trajectory controller settings:
  joint_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - shoulder_rotation
      - forearm_rotation
      - arm_rotation
      - wrist_rotation
      - wrist_pitch
      - gripper_rotation

    constraints:
    goal_time: 0.5                   # Override default
    stopped_velocity_tolerance: 0.02 # Override default
    head_1_joint:
      trajectory: 0.05               # Not enforced if unspecified
      goal: 0.02                     # Not enforced if unspecified
    head_2_joint:
      goal: 0.01                     # Not enforced if unspecified

    state_publish_rate:  50            # Override default
    action_monitor_rate: 50            # Override default
    stop_trajectory_duration: 0        # Override default

    gains:
      shoulder_rotation: {p: 100,  d: 1, i: 1, i_clamp: 1}
      forearm_rotation: {p: 100,  d: 1, i: 1, i_clamp: 1}
      arm_rotation: {p: 100,  d: 1, i: 1, i_clamp: 1}
      wrist_rotation: {p: 100,  d: 1, i: 1, i_clamp: 1}
      wrist_pitch: {p: 100,  d: 1, i: 1, i_clamp: 1}
      gripper_rotation: {p: 100,  d: 1, i: 1, i_clamp: 1}

# Joint velocity controllers settings
  shoulder_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: shoulder_rotation
    pid: {p: 100.0, i: 2.0, d: 0.0}

  forearm_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: forearm_rotation
    pid: {p: 1200.0, i: 500.0, d: 0.0}

  arm_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: arm_rotation
    pid: {p: 550.0, i: 200.0, d: 0.0}

  wrist_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: wrist_rotation
    pid: {p: 5, i: 0.0, d: 0.0}

  wrist_pitch_controller:
    type: effort_controllers/JointVelocityController
    joint: wrist_pitch
    pid: {p: 5.0, i: 0.0, d: 0.0}

  gripper_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: gripper_rotation
    pid: {p: 5.0, i: 0.0, d: 0.0}