manipulator:
  joint_names: ['shoulder_rotation', 'forearm_rotation', 'arm_rotation', 'wrist_rotation', 'wrist_pitch', 'gripper_rotation', ]

# Joint states controller settings
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


# Joint velocity controllers settings
  shoulder_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: shoulder_rotation
    pid: {p: 100.0, i: 2.0, d: 0.0}

  forearm_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: forearm_rotation
    pid: {p: 1200.0, i: 500.0, d: 0.0}

  arm_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: arm_rotation
    pid: {p: 550.0, i: 200.0, d: 0.0}

  wrist_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: wrist_rotation
    pid: {p: 5, i: 0.0, d: 0.0}

  wrist_pitch_controller:
    type: effort_controllers/JointVelocityController
    joint: wrist_pitch
    pid: {p: 5.0, i: 0.0, d: 0.0}

  gripper_rotation_controller:
    type: effort_controllers/JointVelocityController
    joint: gripper_rotation
    pid: {p: 5.0, i: 0.0, d: 0.0}