manipulator:
  joint_names: ['shoulder_rotation', 'forearm_rotation', 'arm_rotation', 'wrist_rotation', 'wrist_pitch', 'gripper_rotation', ]

# Joint states controller settings
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Joint trajectory controller settings:
  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - shoulder_rotation
      - forearm_rotation
      - arm_rotation
      - wrist_rotation
      - wrist_pitch
      - gripper_rotation

    constraints:
      goal_time: 2.5                   # Override default
      stopped_velocity_tolerance: 0.02 # Override default

    state_publish_rate:  50            # Override default
    action_monitor_rate: 50            # Override default
#    stop_trajectory_duration: 0        # Override default

    # gains:
    #   shoulder_rotation: {p: 20.0, i: 1.0, d: 0.001, i_clamp_min: -10.0, i_clamp_max: 10.0}
    #   forearm_rotation: {p: 200.0, i: 50.0, d: 0.01, i_clamp_min: -5.0, i_clamp_max: 5.0}
    #   arm_rotation: {p: 50.0, i: 200.0, d: 0.0001, i_clamp_min: -100.0, i_clamp_max: 100.0}
    #   wrist_rotation: {p: 5.0, i: 8.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
    #   wrist_pitch: {p: 17.0, i: 10.0, d: 0.0001, i_clamp_min: -1.0, i_clamp_max: 1.0}
    #   gripper_rotation: {p: 1.1, i: 0.5, d: 0.0001, i_clamp_min: -2.0, i_clamp_max: 2.0}