/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 7.0.1   2018-02-18

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_tim.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_usart.h"
#include "dxl_rx64.h"
#include "CAN.h"
#include "ENK.h"
#include "defines.h"

/* Private macro */
#define TIMEOUT 200 //in ms
#define SYSTICK_FREQ 100000000
#define TIMEOUT_CNT SYSTICK_FREQ*TIMEOUT/(1000)
#define BAUDRATE 1000000
/* Private variables */
volatile long keyTimeout = 0;

volatile int16_t baseSpeed = 0;
volatile int16_t forearmSpeed = 0;
volatile int16_t armSpeed = 0;
volatile int16_t wristRotateSpeed = 0;
volatile float wristPitchSpeed = 0;
volatile float wristRollSpeed = 0;
volatile int16_t gripperSpeed = 0;
volatile float angle1 = 150;
volatile float angle2 = 150;


/* Private function prototypes */
void RCC_CONF();
void GPIO_CONF();
void USART_CONF();
void TIM_CONF();
void NVIC_Conf();

void send_char(char, USART_TypeDef*);
/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
void send_string(const char*, USART_TypeDef*);
void sendStartStop(char isOn);


volatile RCC_ClocksTypeDef RCC_Clocks;
int main(void)
{
  RCC_CONF();
  GPIO_CONF();
  USART_CONF();
  NVIC_Conf();
  //ENK3init();
  //ENK2init();
  TIM_CONF();
  initCan();

  uint8_t params[5] = {0x06, 0x00, 0x00, 0xFF, 0x03};
  setServoDiode(0x01, 0x01);
  enableTorque(0x01, 0x01);
  setServoTorque(0x01, 1023);
  sendServoCommand(0x01, WRITE, 0x05, params );
  setServoAngle(0x01, angle1);

  setServoDiode(0x02, 0x01);
  enableTorque(0x02, 0x01);
  setServoTorque(0x02, 1023);
  sendServoCommand(0x02, WRITE, 0x05, params );
  setServoAngle(0x02, angle2);

  while (1)
  {
  }
}

/* Private functions */

// Clock configuration and initialization:
void RCC_CONF(){
	//SYSCLK 100MHz:
	RCC_DeInit();

	RCC_HSEConfig(RCC_HSE_ON);
	while(RCC_WaitForHSEStartUp() != SUCCESS);

	RCC_PLLConfig(RCC_PLLSource_HSE, 4, 144, 2, 4);
	RCC_HCLKConfig(RCC_SYSCLK_Div1);
	RCC_PCLK1Config(RCC_HCLK_Div4);
	RCC_PCLK2Config(RCC_HCLK_Div2);
	RCC_SYSCLKConfig(RCC_SYSCLKSource_PLLCLK);
	RCC_PLLCmd(ENABLE);
	while(RCC_GetFlagStatus(RCC_FLAG_PLLRDY) != SET);

	//SysTick initialisation:
	SysTick_Config(TIMEOUT_CNT);
};

void GPIO_CONF(){

	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOB, ENABLE);
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOC, ENABLE);
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOE, ENABLE);

	//MOTOR_1_PWM:

	GPIO_InitTypeDef GPIO_InitStructure;
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_8;
	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_100MHz;
	GPIO_Init(GPIOB, &GPIO_InitStructure);
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource8, GPIO_AF_TIM4);

	//MOTOR_2_PWM:

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_2;
	GPIO_Init(GPIOA, &GPIO_InitStructure);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource2, GPIO_AF_TIM2);

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_6;
    GPIO_Init(GPIOA, &GPIO_InitStructure);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource6, GPIO_AF_TIM3);

	//MOTOR_3_PWM:

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_3;
	GPIO_Init(GPIOA, &GPIO_InitStructure);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource2, GPIO_AF_TIM2);

	//MOTOR_4_PWM:

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_15;
	GPIO_Init(GPIOA, &GPIO_InitStructure);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource15, GPIO_AF_TIM2);

	//MOTOR_5_PWM:

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_3;
	GPIO_Init(GPIOB, &GPIO_InitStructure);
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource3, GPIO_AF_TIM2);

	//MOTOR_6_PWM:

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_9;
	GPIO_Init(GPIOB, &GPIO_InitStructure);
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource9, GPIO_AF_TIM4);

	//BM_PWM:

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_10;
	GPIO_Init(GPIOB, &GPIO_InitStructure);
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource10, GPIO_AF_TIM2);

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_11;
	GPIO_Init(GPIOB, &GPIO_InitStructure);
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource11, GPIO_AF_TIM2);

	//Servo PWM:

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_4 | GPIO_Pin_5;
	GPIO_Init(GPIOB, &GPIO_InitStructure);
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource4, GPIO_AF_TIM3);
	GPIO_PinAFConfig(GPIOB, GPIO_PinSource5, GPIO_AF_TIM3);

	//MOTOR_1_IN gripper:

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_2 | GPIO_Pin_3;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(GPIOE, &GPIO_InitStructure);
	GPIO_ResetBits(GPIOE, GPIO_Pin_3);
	GPIO_ResetBits(GPIOE, GPIO_Pin_2);

	//MOTOR_2_IN gripper:

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_13 | GPIO_Pin_14;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(GPIOC, &GPIO_InitStructure);
	GPIO_ResetBits(GPIOC, GPIO_Pin_13);
	GPIO_ResetBits(GPIOC, GPIO_Pin_14);

	/*//MOTOR_3_IN:

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_15;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(GPIOC, &GPIO_InitStructure);
	GPIO_ResetBits(GPIOC, GPIO_Pin_15);

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_2;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(GPIOD, &GPIO_InitStructure);
	GPIO_ResetBits(GPIOD, GPIO_Pin_2);*/

	//MOTOR_4_IN (first degree):

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_0 | GPIO_Pin_1;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(GPIOD, &GPIO_InitStructure);
	GPIO_SetBits(GPIOD, GPIO_Pin_0);
	GPIO_ResetBits(GPIOD, GPIO_Pin_1);

	//MOTOR_5_IN: (third degree)

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_4 | GPIO_Pin_7;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(GPIOD, &GPIO_InitStructure);
	GPIO_SetBits(GPIOD, GPIO_Pin_4);
	GPIO_ResetBits(GPIOD, GPIO_Pin_7);

	//MOTOR_6_IN: (fourth degree)

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_0 | GPIO_Pin_4;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(GPIOE, &GPIO_InitStructure);
	GPIO_SetBits(GPIOE, GPIO_Pin_4);
	GPIO_ResetBits(GPIOE, GPIO_Pin_0);

	//BM_ENABLE: (second degree)

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_14 | GPIO_Pin_15;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(GPIOE, &GPIO_InitStructure);
	GPIO_SetBits(GPIOE, GPIO_Pin_14);
	GPIO_SetBits(GPIOE, GPIO_Pin_15);

	//LED_GREEN:
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_2;
	GPIO_Init(GPIOB, &GPIO_InitStructure);
	GPIO_ResetBits(GPIOB, GPIO_Pin_2);

	//USART_2:
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_5 | GPIO_Pin_6;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;
	GPIO_Init(GPIOD, &GPIO_InitStructure);

	GPIO_PinAFConfig(GPIOD, GPIO_PinSource5, GPIO_AF_USART2);
	GPIO_PinAFConfig(GPIOD, GPIO_PinSource6, GPIO_AF_USART2);

	//USART_1:
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_9 | GPIO_Pin_10;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;
	GPIO_Init(GPIOA, &GPIO_InitStructure);

	GPIO_PinAFConfig(GPIOA, GPIO_PinSource9, GPIO_AF_USART1);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource10, GPIO_AF_USART1);

	//Encoder_3:
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_9 | GPIO_Pin_11;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
	GPIO_Init(GPIOE, &GPIO_InitStructure);
	GPIO_ResetBits(GPIOE, GPIO_Pin_9);
	GPIO_ResetBits(GPIOE, GPIO_Pin_11);

	//Encoder_4:
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_9 | GPIO_Pin_11;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
	GPIO_Init(GPIOE, &GPIO_InitStructure);
	GPIO_ResetBits(GPIOE, GPIO_Pin_9);
	GPIO_ResetBits(GPIOE, GPIO_Pin_11);

};

void USART_CONF(){
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_USART2, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_USART1, ENABLE);
	USART_InitTypeDef USART_Init_Structure;

	USART_Init_Structure.USART_BaudRate = 1000000;
	USART_Init_Structure.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
	USART_Init_Structure.USART_WordLength = USART_WordLength_8b;
	USART_Init_Structure.USART_StopBits = USART_StopBits_1;
	USART_Init_Structure.USART_Parity = USART_Parity_No;
	USART_Init_Structure.USART_Mode = USART_Mode_Rx | USART_Mode_Tx;
	USART_Init(USART2, &USART_Init_Structure);
	USART_Cmd(USART2, ENABLE);

	//RS-485:
	dxl_uart_init(USART1,BAUDRATE);
}

void TIM_CONF(){

	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM4, ENABLE);

	TIM_TimeBaseInitTypeDef TIM_InitStructure;//50 MHz clock
	TIM_InitStructure.TIM_Prescaler = 50; // 1 MHz
	TIM_InitStructure.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_InitStructure.TIM_Period = 1000; //1 KHz
	TIM_InitStructure.TIM_ClockDivision = TIM_CKD_DIV1;
	TIM_InitStructure.TIM_RepetitionCounter = 0;
	TIM_TimeBaseInit(TIM4, &TIM_InitStructure);

	TIM_OCInitTypeDef TIM_OCInitStruct;
	TIM_OCInitStruct.TIM_OCMode = TIM_OCMode_PWM1;
	TIM_OCInitStruct.TIM_OutputState = TIM_OutputState_Enable;
	TIM_OCInitStruct.TIM_OCPolarity = TIM_OCPolarity_High;
	TIM_OCInitStruct.TIM_Pulse = 0; //50%

	TIM_OC3Init(TIM4, &TIM_OCInitStruct);
	TIM_OC3PreloadConfig(TIM4, TIM_OCPreload_Enable);
	TIM_OC4Init(TIM4, &TIM_OCInitStruct);
	TIM_OC4PreloadConfig(TIM4, TIM_OCPreload_Enable);
	TIM_Cmd(TIM4, ENABLE);

	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM3, ENABLE);
	//50 MHz clock
	TIM_InitStructure.TIM_Prescaler = 50; // 200 kHz
	TIM_InitStructure.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_InitStructure.TIM_Period = 1000; //1 KHz
	TIM_InitStructure.TIM_ClockDivision = TIM_CKD_DIV1;
	TIM_InitStructure.TIM_RepetitionCounter = 0;
	TIM_TimeBaseInit(TIM3, &TIM_InitStructure);

	TIM_OCInitStruct.TIM_OCMode = TIM_OCMode_PWM1;
	TIM_OCInitStruct.TIM_OutputState = TIM_OutputState_Enable;
	TIM_OCInitStruct.TIM_OCPolarity = TIM_OCPolarity_High;
	TIM_OCInitStruct.TIM_Pulse = 0; //10%

	TIM_OC1Init(TIM3, &TIM_OCInitStruct);
	TIM_OC1PreloadConfig(TIM3, TIM_OCPreload_Enable);
	TIM_OC2Init(TIM3, &TIM_OCInitStruct);
	TIM_OC2PreloadConfig(TIM3, TIM_OCPreload_Enable);
	TIM_Cmd(TIM3, ENABLE);

	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);

	TIM_InitStructure.TIM_Prescaler = 50; // 1 MHz
	TIM_InitStructure.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_InitStructure.TIM_Period = 1000; //1 KHz
	TIM_InitStructure.TIM_ClockDivision = TIM_CKD_DIV1;
	TIM_InitStructure.TIM_RepetitionCounter = 0;
	TIM_TimeBaseInit(TIM2, &TIM_InitStructure);

	TIM_OCInitStruct.TIM_OCMode = TIM_OCMode_PWM1;
	TIM_OCInitStruct.TIM_OutputState = TIM_OutputState_Enable;
	TIM_OCInitStruct.TIM_OCPolarity = TIM_OCPolarity_High;
	TIM_OCInitStruct.TIM_Pulse = 0;

	TIM_OC1Init(TIM2, &TIM_OCInitStruct);
	TIM_OC1PreloadConfig(TIM2, TIM_OCPreload_Enable);
	TIM_OC2Init(TIM2, &TIM_OCInitStruct);
	TIM_OC2PreloadConfig(TIM2, TIM_OCPreload_Enable);
	TIM_OC3Init(TIM2, &TIM_OCInitStruct);
	TIM_OC3PreloadConfig(TIM2, TIM_OCPreload_Enable);
	TIM_OC4Init(TIM2, &TIM_OCInitStruct);
	TIM_OC4PreloadConfig(TIM2, TIM_OCPreload_Enable);
	TIM_Cmd(TIM2, ENABLE);

	RCC_APB2PeriphClockCmd(RCC_APB2Periph_TIM1, ENABLE);

    TIM_InitStructure.TIM_Prescaler = 50; // 1 MHz
	TIM_InitStructure.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_InitStructure.TIM_Period = 1000; //1 KHz
	TIM_InitStructure.TIM_ClockDivision = TIM_CKD_DIV1;
	TIM_InitStructure.TIM_RepetitionCounter = 0;
	TIM_TimeBaseInit(TIM1, &TIM_InitStructure);

};

void NVIC_Conf(){
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_0);

    NVIC_InitTypeDef NVIC_InitStruct;
	NVIC_InitStruct.NVIC_IRQChannel = USART2_IRQn;
	NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority = 0;
	NVIC_InitStruct.NVIC_IRQChannelSubPriority = 0;
	NVIC_InitStruct.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&NVIC_InitStruct);

	NVIC_SetPriority(USART2_IRQn, 1);
	NVIC_EnableIRQ(USART2_IRQn);

	USART_ITConfig(USART2, USART_IT_RXNE, ENABLE);
}

//Sending data over USART:

void send_char(char c, USART_TypeDef* USART)
{
    while (USART_GetFlagStatus(USART, USART_FLAG_TXE) == RESET);
    USART_SendData(USART, c);
}

void send_string(const char* s, USART_TypeDef* USART)
{
    while (*s)
        send_char(*s++, USART);
}

//void USART1_IRQHandler (void)
//{
//	// check if the USART1 receive interrupt flag was set
//	if (USART_GetITStatus (USART1, USART_IT_RXNE))
//	{
//		const uint8_t byte = (uint8_t)USART_ReceiveData (USART1); // grab the byte from the data register
//
//        receiveBufferEnd++;
//        if (receiveBufferEnd >= receiveBuffer + REC_BUFFER_LEN)
//            receiveBufferEnd = receiveBuffer;
//
//        *receiveBufferEnd = byte;
//	}
//}

void USART2_IRQHandler (void) {
	   if(USART_GetITStatus(USART2, USART_IT_RXNE))
	   {
		   keyTimeout = 0;
		   char received = USART_ReceiveData(USART2);
		   send_char(received, USART2);
		   switch(received)
		        {
		            case 'a':
		            	GPIO_SetBits(GPIOD, GPIO_Pin_0);
		            	GPIO_ResetBits(GPIOD, GPIO_Pin_1);
		            	TIM_SetCompare1(TIM2,400);
		                break;
		            case 'q':
		            	GPIO_ResetBits(GPIOD, GPIO_Pin_0);
		            	GPIO_SetBits(GPIOD, GPIO_Pin_1);
		            	TIM_SetCompare1(TIM2,400);
		                break;
		            case 'w':
		            	TIM_SetCompare3(TIM2,250);
		            	TIM_SetCompare4(TIM2,0);
		                break;
		            case 's':
		            	TIM_SetCompare3(TIM2,0);
		            	TIM_SetCompare4(TIM2,250);
		                break;
		            case 'e':
		            	GPIO_SetBits(GPIOD, GPIO_Pin_4);
		            	GPIO_ResetBits(GPIOD, GPIO_Pin_7);
		            	TIM_SetCompare2(TIM2,1000);
		                break;
		            case 'd':
		            	GPIO_ResetBits(GPIOD, GPIO_Pin_4);
		            	GPIO_SetBits(GPIOD, GPIO_Pin_7);
		            	TIM_SetCompare2(TIM2,1000);
		                break;
		            case 'r':
		            	GPIO_SetBits(GPIOE, GPIO_Pin_0);
		            	GPIO_ResetBits(GPIOE, GPIO_Pin_4);
		            	TIM_SetCompare4(TIM4,200);
		                break;
		            case 'f':
		            	GPIO_ResetBits(GPIOE, GPIO_Pin_0);
		            	GPIO_SetBits(GPIOE, GPIO_Pin_4);
		            	GPIO_SetBits(GPIOB, GPIO_Pin_2);
		            	TIM_SetCompare4(TIM4,200);
		                break;
		            case 't':
		            	GPIO_ResetBits(GPIOE, GPIO_Pin_3);
		                GPIO_SetBits(GPIOE, GPIO_Pin_2);
		            	GPIO_ResetBits(GPIOC, GPIO_Pin_13);
		                GPIO_SetBits(GPIOC, GPIO_Pin_14);
		                TIM_SetCompare3(TIM4, 300);
		            	TIM_SetCompare1(TIM3, 300);
		                break;
		            case 'g':
		            	GPIO_SetBits(GPIOE, GPIO_Pin_3);
		                GPIO_ResetBits(GPIOE, GPIO_Pin_2);
		            	GPIO_SetBits(GPIOC, GPIO_Pin_13);
		                GPIO_ResetBits(GPIOC, GPIO_Pin_14);
		                TIM_SetCompare1(TIM3, 300);
		            	TIM_SetCompare3(TIM4, 300);
		                break;
		            case 'h':
		            	TIM_SetCompare1(TIM3,400);
		            	TIM_SetCompare2(TIM3,400);
		            	break;
		            case 'u':
						angle1+= 1;
						if(angle1 > 300)
						{
							angle1 = 300;
						}
						setServoAngle(0x01, angle1);
						angle2-=1;
						if(angle2 < 0)
						{
							angle2 = 0;
						}
						setServoAngle(0x02,angle2);
		            	send_string("RS_SEND", USART2);
		            	break;
		            case 'j':
						angle1-= 1;
						if(angle1 < 0)
						{
							angle1 = 0;
						}
						setServoAngle(0x01, angle1);
						angle2+=1;
						if(angle2 > 300)
						{
							angle2 = 300;
						}
						setServoAngle(0x02,angle2);
		            	send_string("RS_SEND", USART2);
		            	break;
		            case 'i':
						angle1+= 1;
						if(angle1 > 300)
						{
							angle1 = 300;
						}
						setServoAngle(0x01, angle1);
						angle2+=1;
						if(angle2 > 300)
						{
							angle2 = 300;
						}
						setServoAngle(0x02,angle2);
		            	send_string("RS_SEND", USART2);
		            	break;
		            case 'k':
						angle1-= 1;
						if(angle1 < 0)
						{
							angle1 = 0;
						}
						setServoAngle(0x01, angle1);
						angle2-=1;
						if(angle2 < 0)
						{
							angle2 = 0;
						}
						setServoAngle(0x02,angle2);
		            	send_string("RS_SEND", USART2);
		            	break;

		            default:
		            	TIM_SetCompare1(TIM2,0);
		            	TIM_SetCompare2(TIM2,0);
		            	TIM_SetCompare3(TIM2,0);
		            	TIM_SetCompare4(TIM2,0);
		            	TIM_SetCompare1(TIM3,0);
		            	TIM_SetCompare2(TIM3,0);
		            	TIM_SetCompare3(TIM4,0);
		            	TIM_SetCompare4(TIM4,0);
		                break;
		        }
	      USART_ClearITPendingBit(USART2, USART_FLAG_RXNE);
	      GPIO_ResetBits(GPIOB, GPIO_Pin_2);
	   }
}

void CAN1_RX0_IRQHandler(void) {
	if (CAN_GetITStatus(CAN1, CAN_IT_FMP0) != RESET) {
		CAN_ClearITPendingBit(CAN1, CAN_IT_FMP0);
		//odebrane dane w strukturze 'rxMessage'
		CAN_Receive(CAN1, CAN_FIFO0, &rxMessage);
		int8_t temp = 0;
		switch (rxMessage.StdId) {
		case 101:
			//Motors start/stop:
			keyTimeout = 0;
			sendStartStop(rxMessage.Data[0]);
			break;
		case 160:
			//Set motors velocity:
			keyTimeout = 0;
			temp = rxMessage.Data[0];
			baseSpeed = temp*1000/100;
			if(baseSpeed < 0)
			{
				GPIO_SetBits(GPIOD, GPIO_Pin_0);
				GPIO_ResetBits(GPIOD, GPIO_Pin_1);
				baseSpeed = (-1)*baseSpeed;
			}
			else
			{
				GPIO_ResetBits(GPIOD, GPIO_Pin_0);
				GPIO_SetBits(GPIOD, GPIO_Pin_1);
			}
		    TIM_SetCompare1(TIM2,baseSpeed);

		    temp = rxMessage.Data[1];
		    int forearmSpeed = temp*1000/100;
			if(forearmSpeed < 0)
			{
				forearmSpeed = (-1)*forearmSpeed;
            	TIM_SetCompare3(TIM2,forearmSpeed);
            	TIM_SetCompare4(TIM2,0);
			}
			else
			{
            	TIM_SetCompare3(TIM2,0);
            	TIM_SetCompare4(TIM2,forearmSpeed);
			}

			temp = rxMessage.Data[2];
			armSpeed = temp*1000/100;
			if(armSpeed < 0)
			{
				armSpeed = (-1)*armSpeed;
            	GPIO_SetBits(GPIOD, GPIO_Pin_4);
            	GPIO_ResetBits(GPIOD, GPIO_Pin_7);
			}
			else
			{
            	GPIO_ResetBits(GPIOD, GPIO_Pin_4);
            	GPIO_SetBits(GPIOD, GPIO_Pin_7);
			}
			TIM_SetCompare2(TIM2,armSpeed);

			temp = rxMessage.Data[3];
			wristRotateSpeed = temp*1000/100;
			if(wristRotateSpeed < 0)
			{
				wristRotateSpeed = (-1)*wristRotateSpeed;
            	GPIO_SetBits(GPIOE, GPIO_Pin_0);
            	GPIO_ResetBits(GPIOE, GPIO_Pin_4);
			}
			else
			{
            	GPIO_ResetBits(GPIOE, GPIO_Pin_0);
            	GPIO_SetBits(GPIOE, GPIO_Pin_4);
			}
			TIM_SetCompare4(TIM4,wristRotateSpeed);

			temp = rxMessage.Data[4];
			wristPitchSpeed = (float)temp/10;
			if(wristPitchSpeed < 0)
			{
				wristPitchSpeed = (-1)*wristPitchSpeed;
				angle1+= wristPitchSpeed;
				if(angle1 > 300)
				{
					angle1 = 300;
				}
				setServoAngle(0x01, angle1);
				angle2-= wristPitchSpeed;
				if(angle2 < 0)
				{
					angle2 = 0;
				}
				setServoAngle(0x02,angle2);
//				uint16_t firstServoSpeed = ((1023*wristPitchSpeed)/100);
//				uint16_t secondServoSpeed = ((1023*wristPitchSpeed)/100) + 1024;
//            	setServoSpeed(0x02, (uint8_t)(firstServoSpeed >> 8), (uint8_t)(firstServoSpeed));
//            	setServoSpeed(0x01, (uint8_t)(secondServoSpeed >> 8), (uint8_t)(secondServoSpeed));
			}
			else if(wristPitchSpeed > 0)
			{
				angle1-= wristPitchSpeed;
				if(angle1 < 0)
				{
					angle1 = 0;
				}
				setServoAngle(0x01, angle1);
				angle2+=wristPitchSpeed;
				if(angle2 > 300)
				{
					angle2 = 300;
				}
				setServoAngle(0x02,angle2);
			}

			temp = rxMessage.Data[5];
			wristRollSpeed = (float)temp/10;
			if(wristRollSpeed < 0)
			{
				wristRollSpeed = (-1)*wristRollSpeed;
				angle1+= wristRollSpeed;
				if(angle1 > 300)
				{
					angle1 = 300;
				}
				setServoAngle(0x01, angle1);
				angle2+=wristRollSpeed;
				if(angle2 > 300)
				{
					angle2 = 300;
				}
				setServoAngle(0x02,angle2);
//				uint16_t firstServoSpeed = ((1023*wristRollSpeed)/100) + 1024;
//				uint16_t secondServoSpeed = ((1023*wristRollSpeed)/100) + 1024;
//            	setServoSpeed(0x02, (uint8_t)(firstServoSpeed >> 8), (uint8_t)(firstServoSpeed));
//            	setServoSpeed(0x01, (uint8_t)(secondServoSpeed >> 8), (uint8_t)(secondServoSpeed));
			}
			else if(wristRollSpeed > 0)
			{
				angle1-= wristRollSpeed;
				if(angle1 < 0)
				{
					angle1 = 0;
				}
				setServoAngle(0x01, angle1);
				angle2-=wristRollSpeed;
				if(angle2 < 0)
				{
					angle2 = 0;
				}
				setServoAngle(0x02,angle2);
//				uint16_t firstServoSpeed = ((1023*wristRollSpeed)/100);
//				uint16_t secondServoSpeed = ((1023*wristRollSpeed)/100);
//            	setServoSpeed(0x01, (uint8_t)(firstServoSpeed >> 8), (uint8_t)(firstServoSpeed));
//            	setServoSpeed(0x02, (uint8_t)(secondServoSpeed >> 8), (uint8_t)(secondServoSpeed));
			}

			temp = rxMessage.Data[6];
			gripperSpeed = temp*1000/300;
			if(gripperSpeed < 0)
			{
				gripperSpeed = (-1)*gripperSpeed;
            	GPIO_ResetBits(GPIOE, GPIO_Pin_3);
                GPIO_SetBits(GPIOE, GPIO_Pin_2);
            	GPIO_ResetBits(GPIOC, GPIO_Pin_13);
                GPIO_SetBits(GPIOC, GPIO_Pin_14);
                TIM_SetCompare3(TIM4, gripperSpeed);
            	TIM_SetCompare1(TIM3, gripperSpeed);
			}
			else
			{
            	GPIO_SetBits(GPIOE, GPIO_Pin_3);
                GPIO_ResetBits(GPIOE, GPIO_Pin_2);
            	GPIO_SetBits(GPIOC, GPIO_Pin_13);
                GPIO_ResetBits(GPIOC, GPIO_Pin_14);
                TIM_SetCompare1(TIM3, gripperSpeed);
            	TIM_SetCompare3(TIM4, gripperSpeed);
			}

			break;
		case 162:
			//Motors start/stop:
			keyTimeout = 0;
			sendStartStop(rxMessage.Data[0]);
			break;
		default:
			break;
		}
	}
}

void sendStartStop(char isOn)
{
	if(isOn != '1')
	{
    	TIM_SetCompare1(TIM2,0);
    	TIM_SetCompare2(TIM2,0);
    	TIM_SetCompare3(TIM2,0);
    	TIM_SetCompare4(TIM2,0);
    	TIM_SetCompare1(TIM3,0);
    	TIM_SetCompare2(TIM3,0);
    	TIM_SetCompare3(TIM4,0);
    	TIM_SetCompare4(TIM4,0);
	}
	else
	{

	}
}



void SysTick_Handler(void)
{
	if(keyTimeout++ > TIMEOUT)
	{
    	TIM_SetCompare1(TIM2,0);
    	TIM_SetCompare2(TIM2,0);
    	TIM_SetCompare3(TIM2,0);
    	TIM_SetCompare4(TIM2,0);
    	TIM_SetCompare1(TIM3,0);
    	TIM_SetCompare2(TIM3,0);
    	TIM_SetCompare3(TIM4,0);
    	TIM_SetCompare4(TIM4,0);
//    	uint8_t params[5] = {0x06, 0x00, 0xFF, 0x03};
//    	sendServoCommand(0x02, WRITE, 0x05, params );
//    	enableTorque(0x02, 0x00);
//    	sendServoCommand(0x01, WRITE, 0x05, params );
//    	enableTorque(0x01, 0x00);

		keyTimeout = 0;
	}
	TimingDelay_Decrement();
}

volatile uint16_t delayTimer;

void delay(uint16_t time){
	delayTimer= time;
	while(delayTimer!=0){
		;
	}
}

void TimingDelay_Decrement(void){
	if(delayTimer>0){
		delayTimer--;
	}
}

int16_t PID(uint16_t Kp, uint16_t Kd, uint16_t KI, float targetVelocity, float currentVelocity, int16_t ErrorSum) {

	int16_t Error = targetVelocity - currentVelocity;
	ErrorSum = Error + ErrorSum;
	if (ErrorSum > 1000)
		ErrorSum = 1000;
	else if (ErrorSum < -1000)
		ErrorSum = -1000;

	int16_t ErrorTemp = Error-ErrorTemp;
	int16_t PWM = Kp * Error - ErrorTemp + Kd * (Error ); //PreviousError)+ Ki * ErrorSum;
	//PreviousError = Error;
	return PWM;
}
