/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 7.0.1   2019-07-21

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */

#include "stm32f4xx.h"
#include "FreeRTOS.h"
#include "task.h"

#include "ManipulatorStateMachine.h"
#include "Utility.h"

#ifdef __cplusplus
extern "C" {
#endif

	void vApplicationTickHook( void );
	void vApplicationIdleHook( void );

#ifdef __cplusplus
}
#endif


void stateMachineTaskHandler(void* params);

ManipulatorStateMachine manipulator;

QueueHandle_t usartQueue;
QueueHandle_t rs485Queue;

cyclicBuffer msgBuffer;
volatile ManipulatorMsg msg;

cyclicBuffer servoBuffer;
volatile ServoResponse servoMsg;

TaskHandle_t stateMachineTask = NULL;
TaskHandle_t usartTxTask = NULL;

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

int main(void)
{
	uint8_t status = RCC_CONF();
	usartQueue = xQueueCreate(1, sizeof(ManipulatorMsg*));
	if(status == 0)
	{
		SystemCoreClockUpdate();
		xTaskCreate(stateMachineTaskHandler, "StateMachineTask",
					configMINIMAL_STACK_SIZE, NULL, 2,
					&stateMachineTask);
	}

	vTaskStartScheduler();

//  uint8_t params[5] = {0x06, 0x00, 0x00, 0xFF, 0x03};
//  setServoDiode(0x01, 0x01);
//  enableTorque(0x01, 0x01);
//  setServoTorque(0x01, 1023);
//  sendServoCommand(0x01, WRITE, 0x05, params );
//  setServoAngle(0x01, angle1);
//
//  setServoDiode(0x02, 0x01);
//  enableTorque(0x02, 0x01);
//  setServoTorque(0x02, 1023);
//  sendServoCommand(0x02, WRITE, 0x05, params );
//  setServoAngle(0x02, angle2);

  while (1){};
}

/* Private functions */

void stateMachineTaskHandler(void* params)
{
	manipulator.run();
}

void vApplicationTickHook( void )
{

}

void vApplicationIdleHook( void )
{
	__WFI();
}
